repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace  

  - repo: local
    hooks:
      - id: betty
        name: betty-style
        description: Check betty style.
        entry: betty
        language: system
        files: \.(c|h)$